#version: "3.8"
#services:
#  server:
#    build: .
#    restart: always
#    ports:
#      - 8080:8080
#    depends_on:
#      - mysqldb
#  mysqldb:
#    platform: linux/x86_64
#    image: "mysql:5.7"
#    restart: always
#    ports:
#      - 3307:3306
#    environment:
#      MYSQL_DATABASE: springboot
#      MYSQL_USER: orion
#      MYSQL_PASSWORD: 781227781227
#      MYSQL_ROOT_PASSWORD: 781227781227

version: "3.7"
services:
  server:
    build: .
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysqldb
  mysqldb:
    platform: linux/x86_64
    image: "mysql:8.0.29"
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: blogDB
      MYSQL_ROOT_PASSWORD: root